### ISSUE TITLE
Allow multiple ZK urls and validate them

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#101]
See https://github.com/mesosphere/cassandra-mesos/blob/master/cassandra-mesos-framework/src/main/java/io/mesosphere/mesos/frameworks/cassandra/framework/Main.java

**Comment by frankscholten** [comment]
@tymofii-polekhin Can you test if multiple ZK urls are supported on your cluster?

**Comment by tymofii-polekhin** [comment]
Hello, Frank

I’ve actually have only one master node, so on;y one zk url is available

On Jul 20, 2015, at 3:40 PM, Frank Scholten <notifications@github.com<mailto:notifications@github.com>> wrote:


@tymofii-polekhin<https://github.com/tymofii-polekhin> Can you test if multiple ZK urls are supported on your cluster?

**Comment by philwinder** [comment]
There are unit tests in the code to make sure this works. We just need to try in real life. I could try on my DCOS cluster?

**Comment by philwinder** [comment]
I have tested this on a HA DCOS cluster (3 masters, with 3 zk instances).
It works, but only in a very specific format. This is because the mesos zk code requires the zk url in a ridiculously strict format. So, this marathon command definitely works, but we should refactor our command line arguments and zk code to make it easier for our users. See #169 
```
{
  "id": "elasticsearch",
  "cpus": 0.2,
  "mem": 512,
  "instances": 1,
  "args": ["-zk", "zk://52.18.220.27:2181,52.18.220.101:2181,52.18.220.12:2181/mesos", "-n", "3"],
  "env": {
    "JAVA_OPTS": "-Xms128m -Xmx256m"
  },
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "pnwtrifork/elasticsearch-scheduler-test",
      "network": "HOST",
      "forcePullImage": true   
    }
  }
}
```
Note that the zk urls MUST NOT have znode paths appended on any of the urls EXCEPT the last one. The zk url MUST have a znode path appended to the end of the last URL. This is a requirement by mesos.
