### ISSUE TITLE
Handling of ZK defaults in scheduler

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#273]
The ZK address handling is a little brittle since the zkURL is parsed on the input, but then parsed again on the executor.

Suggest using raw ZK URLs until required. Suggest waiting until it becomes a problem. Low priority.

If anyone actually does this refactoring, be really careful which ZKFormatter is used. Mesos, the Elasticsearch plugin and the framework all have very subtly different ZK formats, due to no ZK URL specification.

**Comment by WalterDalton** [comment]
This, I believe is causing an issue for me in that my Mesos ZK path isn't being taken by the --zookeeperMesosUrl  Basically, I am putting /mesosha at the end of the ZK string per what my Mesos nodes are using, but when it tries to start, it's just trying to connect /mesos (based on the logs) and executors never get spun up (my guess is due to a failure to registry with Mesos).

**Comment by frankscholten** [comment]
@WalterDalton Thanks for reporting. We are fixing this issue as part of https://github.com/mesos/elasticsearch/issues/483 in 0.7.2
