### ISSUE TITLE
Resources are not requested as a role

### ISSUE THREAD

**Issue by philwinder** [mesos/elasticsearch#284]
Resources should be requested as a role, else they are requested as *. 

The role should be set for each resource requested. E.g. should be setRole in here:
https://github.com/mesos/elasticsearch/blob/master/scheduler/src/main/java/org/apache/mesos/elasticsearch/scheduler/Resources.java#L21

See Kafka for an example:
https://github.com/mesos/kafka/commit/64b5a1d08af9ff80b72d6dcfefffdf3ec5ab7bdf#diff-80847d72b150ee9db41881483cd67fc4R475

**Comment by jhftrifork** [comment]
Update: tests for this currently fail because registration is denied to any scheduler registering with a role other than `*`:

```
I0909 09:33:15.562909    30 sched.cpp:264] No credentials provided. Attempting to register without authentication
I0909 09:33:15.564353    30 sched.cpp:815] Got error 'Role 'someframeworkrole' is invalid'
```

This is because mini-mesos does not have ACLs enabled.

[The ACL/role feature in Mesos is enabled by passing a JSON configuration in a `--acls` command-line parameter when starting a Mesos master.](http://mesos.apache.org/documentation/latest/authorization/)

[These flags are configured in the mesos-local Docker project.](https://github.com/ContainerSolutions/mesos-local/blob/5c52ffdef333ce9067c98b14f17f5255a2a8bf60/supervisor.conf#L13)

The JSON configuration can either be a plain string or a file reference, but either way, the ACL is configured at the time the Mesos master is launched. So in the mini-mesos API, the ACL config needs to be passed to the new `MesosCluster` in the `MesosClusterConfig` argument.

mini-mesos can then pass the ACL as a JSON-formatted environment variable to Docker. [These environment variables are then available in run.sh](https://github.com/ContainerSolutions/mesos-local/blob/5c52ffdef333ce9067c98b14f17f5255a2a8bf60/run.sh#L27) and are passed to the `supervisord` call, so the environment variables will also be available [in supervisor.conf here](https://github.com/ContainerSolutions/mesos-local/blob/5c52ffdef333ce9067c98b14f17f5255a2a8bf60/supervisor.conf#L13), so we can substitute it as the `--acls` command-line argument there.

**Comment by philwinder** [comment]
Fixed in:https://github.com/mesos/elasticsearch/pull/281
And: https://github.com/mesos/elasticsearch/pull/296
