### ISSUE TITLE
dataDir is not working when in nonDocker mode

### ISSUE THREAD

**Issue by tymofii-polekhin** [mesos/elasticsearch#431]
Applied a dirty hack to make it work:
`launcher.addRuntimeSettings(ImmutableSettings.builder().put("path.data", "/tmp/mesos/elasticsearch"));`

But really should work in both modes.

**Comment by philwinder** [comment]
This is intentional. The dataDir is intended to mount a docker volume to the host. This is a case of bad naming. If you want to change any of the ES settings, then please provide your own ES yml settings file that is accessible by all of the hosts and set the path to that file in the `—elasticsearchSettingsLocation`.

I will open another issue to consider renaming the dataDir parameter to make the fact that it refers to docker volumes more explicit.
