### ISSUE TITLE
Tight coupling between Mesos task data and Web UI.

### ISSUE THREAD

**Issue by alex-glv** [mesos/elasticsearch#448]
Is there a reason for such tight coupling between low-level Mesos task info and Web UI representation of ES node?
Web UI is reporting such info as TaskID, task status (eg TASK_LOST, etc...).

What's the advantage of taking responsibility for maintaining the task information?
I'd rather Web UI get this information from either Mesos API or Elasticsearch API, or external service discovery solution.

One downside to identifying Mesos task as ES node in my opinion is following scenario: 
 - Run scheduler and set --frameworkUseDocker=true.
 - Scheduler accepts an offer, sends TaskInfo with Docker container details and network mode set to  "bridge"

Now, when Mesos starts the task, the executor gets its own network stack and IP address, in this case ES node is not actually listening on Mesos agent IP address, and Scheduler is assuming that Mesos agent IP = ES node IP.

I think a better solution is to have Executor figure its IP address, register with Service Discovery tool (eg Consul), and Scheduler poll healthy ES nodes and keep its internal state in sync. 

Is there anything I am missing?

**Comment by philwinder** [comment]
I think you've mixed a couple of issues there. Executor IP address discovery has nothing to do with the web UI representation.

I don't care so much for the UI, so long as the fundamentals are solid. You're key point is the discovery part, which I totally agree with. However, it's not quite as simple as that. For example, what happens if the executor is ran in JAR mode. How does the executor figure out it's own IP address? Does it come from eth0, wan0, abc123Adaptor, etc. Which adaptor is correct?

The correct answer is the network which is on the same network as Consul. So, you could imagine looping over all adaptors, pinging consul and see if we get a response. When we do, that's the correct network. But even after all that, there is absolutely no guarantee that this ip address is routable from a user's machine.

It's not simple. I'm tempted to investigate a SDN technology, like Calico or Weave.

I'd be happy to talk this over as it does need solving.

**Comment by alex-glv** [comment]
My main concern is providing a "user" with an endpoint to the ES cluster. Scaling also requires more dynamic approach to locating ES nodes.

What if work on the following assumption. If user has access to consul network, then user has also access to all the endpoints stored in consul. We can at least implement it with the ES running in Docker container.

That's for short / medium term discovery solution, until we come up with a better option.

**Comment by philwinder** [comment]
Let's talk on Monday.
