### ISSUE TITLE
elasticsearchPorts option

### ISSUE THREAD

**Issue by luhkevin** [mesos/elasticsearch#544]
I think the delimiter for the` --elasticsearchPorts` option should be documented here: http://mesos-elasticsearch.readthedocs.org/en/latest/

From what I can tell, the delimiter for http/transport ports is a comma.

Also, what exactly can I pass into the `--elasticsearchPorts` option to make it select random ports? I understand that I can just not pass in the option at all, but I've tried giving it `"0,0"` or just the empty string `""`, or two empty strings separated by a comma `"",""` 

But nothing seems to work....

**Comment by philwinder** [comment]
Hi @luhkevin, Yes you are quite right. Sorry for the lack of documentation. I will add now.

The format is: `HTTP_PORT,TRANSPORT_PORT`. Although it is recommended that you don't use this, because Mesos should provide you with the port resources, not the other way around. If you want random ports, then simply don't pass the parameter.
