### ISSUE TITLE
Container version of framework fails on "--frameworkUseDocker false" flag

### ISSUE THREAD

**Issue by tanveergill** [mesos/elasticsearch#573]
I tried passing `--frameworkUseDocker false` to the docker version of elasticsearch scheduler. 
But its failing with weird errors while downloading jar: `Failed to fetch 'http://b6c71a7fe37a:39427/get/public/elasticsearch.tar.gz': Error downloading resource: Couldn't resolve host name`
I believe its using the same internal variable for the identity of the scheduler -- ip address for jar or container id for container.
Maybe no one tested it under the assumption that no one runs scheduler as a container to spin up elasticsearch in jar's.

**Comment by philwinder** [comment]
The issue is described in the error message. The executor is trying to download the default ES binary from the scheduler, which has a hostname of b6c... which is obviously not routable.

You need to make the scheduler routeable, or you can override the location from which it downloads the binary with `--elasticsearchBinaryUrl`. Thanks.
