### ISSUE TITLE
Implement REST API endpoints

### ISSUE THREAD

**Issue by jrslv** [mesos/elasticsearch#87]
The idea is, that we have a REST API that the web UI (and possibly other components in the future) can use to communicate with the Framework Scheduler. The initial documentation and mock is here: http://docs.elasticsearchmesosui.apiary.io/

So far the following is covered in the mock. Please discuss requirements in comments.

- [x] getting elastic search tasks, #109 
- [x] getting cluster info
- [ ] getting scheduler info
- [ ] getting executors info

**Comment by philwinder** [comment]
Nice, Apiary looks nice, if a little over the top.
As an elasticsearch user, my main requirement is to ensure that he cluster has been established and make sure that the cluster health is ok. So I am interested in presenting more ES specific information, rather than Mesos related information. I think the only Mesos info I want to see is just a list of running ES instances, where they are, what ports, etc. I don't really care about the executor info as it mostly contains Mesos under-the-bonnet stuff.

**Comment by mwl** [comment]
Okay @jrslv let's have a look at this :+1:
